service: serverless-FRG


plugins:

  - serverless-python-requirements

  - serverless-wsgi


custom:

  wsgi:

    app: app.app

    packRequirements: false

  pythonRequirements:

    dockerizePip: non-linux


provider:

  name: aws

  runtime: python3.7

  stage: dev

  region: eu-west-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: 'arn:aws:s3:::bucketdemarde/*'

functions:

  app:

    handler: wsgi_handler.handler



    events:

      - http: ANY /

      - http: 'ANY {proxy+}'